

DictProducer.o:DictProducer.h DictProducer.cpp 
	g++ -c DictProducer.cpp -o DictProducer.o

SplitTool.o:SplitTool.h SplitTool.cpp
	g++ -c SplitTool.cpp -o SplitTool.o

DirScanner.o:DirScanner.h DirScanner.cpp
	g++ -c DirScanner.cpp -o DirScanner.o


clean:
	rm *.o
